In [3]:
import numpy as np

In [24]:
a = np.array([
    [1,2,3,4,5],
    [2,3,3,4,5],
    [3,4,3,4,5],
    [5,6,3,4,5]
])

In [25]:
b = np.exp(a)
print(b)

[[   2.71828183    7.3890561    20.08553692   54.59815003  148.4131591 ]
 [   7.3890561    20.08553692   20.08553692   54.59815003  148.4131591 ]
 [  20.08553692   54.59815003   20.08553692   54.59815003  148.4131591 ]
 [ 148.4131591   403.42879349   20.08553692   54.59815003  148.4131591 ]]


In [29]:
c = np.sum(b,axis=1)

d = np.ones(b.shape)
print(d)
d = (d.T*c).T
print(d)

[[ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]]
[[ 233.20418399  233.20418399  233.20418399  233.20418399  233.20418399]
 [ 250.57143908  250.57143908  250.57143908  250.57143908  250.57143908]
 [ 297.78053302  297.78053302  297.78053302  297.78053302  297.78053302]
 [ 774.93879865  774.93879865  774.93879865  774.93879865  774.93879865]]


In [5]:
c=(1.37**2)**-1

In [6]:
c*np.exp(-1)

0.1960037514899261